name: bmi_calculator
description: BMI Calculator app project using Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.6+6

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: '>=3.29.3'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: "^0.14.4"
#flutter_launcher_icons:
#  image_path: "assets/icon/logo.png"
#  background_color: "#ffffff"
#  android: "ic_launcher_background"
#  ios: false
#  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/logo.png
